// modelInference.js
// Loads the TF.js image classification model and runs inference on webcam frames.
//
// IMPORTANT: The model files must be generated by running convert_model.py first.
// They are stored in frontend/public/model/ and served by Vite as static assets:
//   /model/model.json     — model architecture + weight manifest
//   /model/classes.json   — ordered list of class label strings (e.g. ["A","B",...])
//   /model/group1-shard*.bin — weight data referenced by model.json
//
// If loadModel() throws "An InputLayer should be passed either a batchInputShape or an
// inputShape", the model was converted with an incompatible version of tensorflowjs.
// Re-run convert_model.py to regenerate the model files.

import * as tf from '@tensorflow/tfjs';

// Holds the loaded LayersModel after loadModel() succeeds. Null until then.
let model = null;
// Holds the ordered array of class label strings after loadModel() succeeds.
let classNames = null;

export async function loadModel() {
  // Force TF.js to use the WebGL backend (GPU-accelerated via WebGL shaders).
  // Without this, TF.js tries several backends in order and may attempt to fetch
  // WASM binary files from paths that Vite's dev server doesn't serve, causing
  // ERR_FILE_NOT_FOUND errors in the console.
  console.log("")
  
  try {
    await tf.setBackend('webgl');
    console.log("works")
  } catch (e) {
    console.error('tf.setBackend failed:', e);
  }
  // Wait until the backend is fully initialized before loading the model.
  
  try {
    await tf.ready();
    console.log("works")
  } catch (e) {
    console.error('await tf.ready(); failed:', e);
  }

  console.log("reaches")

  // Load both files in parallel to minimize startup time.
  const [loadedModel, res] = await Promise.all([

    // tf.loadLayersModel fetches model.json then automatically fetches the
    // shard .bin files listed in its weightsManifest.
    tf.loadLayersModel('/model/model.json'),
    // classes.json is a plain JSON array, e.g. ["A","B","C",...]
    fetch('/model/classes.json'),
  ]);

  console.log(loadedModel)

  

  model = loadedModel;
  classNames = await res.json();
}

// Returns true only after loadModel() has resolved successfully.
// Used by App.jsx to decide whether to enable the ML Model toggle button.
export function isModelLoaded() {
  return model !== null && classNames !== null;
}

// Offscreen 96×96 canvas used to crop the hand region from the video frame.
// Created once at module load (not inside runModelInference) to avoid GC pressure.
const cropCanvas = document.createElement('canvas');
cropCanvas.width = 96;
cropCanvas.height = 96;
const cropCtx = cropCanvas.getContext('2d');

export function runModelInference(videoElement, landmarks) {
  // Safety guard — should not be called before loadModel() resolves.
  if (!model || !classNames || !landmarks) return '';

  const vw = videoElement.videoWidth;
  const vh = videoElement.videoHeight;

  // landmarks is an array of 21 {x,y,z} points in normalized [0,1] coords.
  // Find the bounding box of all landmark points.
  const xs = landmarks.map((lm) => lm.x);
  const ys = landmarks.map((lm) => lm.y);

  // Add a small padding around the bounding box so the hand isn't clipped.
  const pad = 0.05;
  // Clamp to [0,1] then convert to pixel coords for the drawImage call.
  const x1 = Math.max(0, Math.min(...xs) - pad) * vw;
  const y1 = Math.max(0, Math.min(...ys) - pad) * vh;
  const x2 = Math.min(1, Math.max(...xs) + pad) * vw;
  const y2 = Math.min(1, Math.max(...ys) + pad) * vh;

  const cw = x2 - x1;
  const ch = y2 - y1;

  // If the detected region is too small the crop would be garbage — skip inference.
  if (cw < 20 || ch < 20) return '';

  // Crop the hand region from the video frame and scale it to 96×96.
  cropCtx.drawImage(videoElement, x1, y1, cw, ch, 0, 0, 96, 96);

  // Run inference inside tf.tidy() so intermediate tensors are automatically
  // disposed after the call, preventing GPU memory leaks.
  const preds = tf.tidy(() => {
    const tensor = tf.browser
      .fromPixels(cropCanvas)   // uint8 tensor [96, 96, 3]
      .toFloat()                // cast to float32
      .div(127.5)               // scale to [0, 2]
      .sub(1)                   // shift to [-1, 1]  (MobileNet-style normalization)
      .expandDims(0);           // add batch dim → [1, 96, 96, 3]
    return model.predict(tensor).dataSync(); // returns a Float32Array of class scores
  });

  // Pick the class with the highest score.
  const topIdx = preds.indexOf(Math.max(...preds));
  const confidence = preds[topIdx];

  // Reject low-confidence predictions to avoid displaying junk.
  if (confidence < 0.5) return '';
  return classNames[topIdx];
}
